Improves documentation (#47)
* doc

* remove added file

* doc

* doc update

* fix req

* urls

* remove pyquickhelper

* fix urls

* add embedded

* has_cuda flag

* update doc

* urls

* action

diff --git a/.github/workflows/documentation.yml b/.github/workflows/documentation.yml
--- a/.github/workflows/documentation.yml
+++ b/.github/workflows/documentation.yml
@@ -1,9 +1,15 @@
-name: Documentation
+name: Documentation and Code Coverage
 
-on: [push, pull_request]
+on:
+  push:
+  pull_request:
+    types:
+      - closed
+    branches:
+      - main
 
 jobs:
-  build_wheels:
+  run:
     name: Build documentation on ${{ matrix.os }}
     runs-on: ${{ matrix.os }}
     strategy:
@@ -13,25 +19,72 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
-      # Used to host cibuildwheel
       - uses: actions/setup-python@v4
         with:
-          python-version: '3.10'
+          python-version: '3.11'
+
+      - uses: tlylt/install-graphviz@v1
+
+      - name: Install pandoc
+        run: sudo apt-get install -y pandoc
 
       - name: Install requirements
         run: python -m pip install -r requirements.txt
 
-      - name: Install requirements-dev.txt
+      - name: Install requirements dev
         run: python -m pip install -r requirements-dev.txt
 
-      - name: Install
-        # run: python -m pip install -e . -v -v -v
+      - name: Cache pip
+        uses: actions/cache@v2
+        with:
+          path: ~/.cache/pip
+          key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
+          restore-keys: |
+            ${{ runner.os }}-pip-
+            ${{ runner.os }}-
+
+      - name: Build
+        run: python setup.py build_ext --inplace
+
+      - name: Generate coverage report
         run: |
-          python setup.py build_ext --inplace
-          python setup.py install
+          pip install pytest
+          pip install pytest-cov
+          export PYTHONPATH=.
+          pytest --cov=./onnx_array_api/ --cov-report=xml --durations=10 --ignore-glob=**LONG*.py --ignore-glob=**notebook*.py
+          export PYTHONPATH=
+
+      - name: Upload coverage reports to Codecov
+        uses: codecov/codecov-action@v3
+        env:
+          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
+
+      - name: Install
+        run: python setup.py install
+
+      - name: Copy license, changelogs
+        run: |
+          cp LICENSE* ./_doc
+          cp CHANGELOGS* ./_doc
 
       - name: Documentation
-        run: python -m sphinx ./_doc ./dist/html
+        run: python -m sphinx ./_doc ./dist/html -n -w doc.txt
+
+      - name: Summary
+        run: cat doc.txt
+
+      - name: Check for errors and warnings
+        run: |
+          if [[ $(grep ERROR doc.txt | grep -v 'validation.cuda') ]]; then
+            echo "Documentation produces errors."
+            grep ERROR doc.txt | grep -v 'validation.cuda'
+            exit 1
+          fi
+          if [[ $(grep WARNING doc.txt | grep -v 'validation.cuda') ]]; then
+            echo "Documentation produces warnings."
+            grep WARNING doc.txt | grep -v 'validation.cuda'
+            exit 1
+          fi
 
       - uses: actions/upload-artifact@v3
         with:
